version: "3.9"
   
services:
  db:
    image: postgres:12.0-alpine
    ports: 
      - "5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file: .env.db

  web:
    # build:
    #   context: .
    #   dockerfile: Dockerfile.prod
    image: 344185791014.dkr.ecr.ap-northeast-1.amazonaws.com/hinata_quiz:latest
    command: uwsgi --socket :8000 --master --enable-threads --module hinata_quiz.wsgi
    volumes:
      - static_volume:/vol/web
    # 環境変数を指定
    env_file: .env
    expose: 
      - 8000
    depends_on:
      - db
  
  nginx:
    # build: ./nginx
    image: 344185791014.dkr.ecr.ap-northeast-1.amazonaws.com/hinata_quiz_nginx:latest
    volumes: 
      - static_volume:/vol/static
    ports: 
      - 80:80
    depends_on: 
      - web

volumes:
  db_data:
  static_volume: