# Generated by Django 3.1.3 on 2020-12-23 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
