# Generated by Django 3.1.3 on 2020-12-25 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_quiz_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='statement',
            field=models.TextField(max_length=200, verbose_name='問題文'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='thumbnail_image_url',
            field=models.URLField(max_length=1000, verbose_name='画像URL'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.TextField(max_length=50, verbose_name='クイズタイトル'),
        ),
    ]
